<a href="https://colab.research.google.com/github/tamburins/ESAA-2022-/blob/main/ESAA_09_30_assignment(_131).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

파이썬 머신러닝 완벽가이드

ch2. 1~5
pg. 87 ~ 131



## 02 사이킷런으로 시작하는 머신러닝
### 01 사이킷런 소개와 특징

- 파이썬 기반의 다른 머신러닝 패키지도 사이킷런 스타일의 API를 지향할 정도로 쉽고 가장 파이썬스러운 API

- 머신러닝을 위한 매우 다양한 알고리즘과 개발을 위한 편리한 프레임워크와 API 제공

- 오랜 기간 실전 환경에서 검증, 매우 많은 환경에서 사용

In [1]:
pip install scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import sklearn
print(sklearn.__version__) #사이킷런 버전 확인

1.0.2


### 02 첫 번째 머신러닝 만들어 보기 - 붓꽃 품종 예측하기

분류 = 지도학습

= 학습을 위한 다양한 피처와 분류 결정값인 레이블 데이터로 모델을 학습한 뒤, 별도의 테스트 데이터 세트에서 미지의 레이블을 예측하는 방법

In [3]:
#사이킷런에서 사용할 모듈 임포트
from sklearn.datasets import load_iris #붓꽃 데이터 생성
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split 
# 학습데이터, 검증데이터, 예측 데이터로 데이터를 분리하거나 최적의 하이퍼 파라미터로 평가하기 이한 다양한 모듈의 모임

In [4]:
import pandas as pd

iris=load_iris() #붓꽃 데이터 세트 로딩
iris_data=iris.data #iris.data는 데이터세트에서 feature만으로 된 데이터를 numpy로 가짐

#iris.target은 데이터세트에서 레이블(결정값) 데이터를 numpy로 가짐
iris_label=iris.target
print('iris target값:', iris_label)
print('iris target명: ', iris.target_names)

#붓꽃 데이터 세트를 자세히 보기 위해 dataframe으로 변환
iris_df=pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(3)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명:  ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [5]:
#학습용 데이터와 테스트용 데이터 분리

X_train, X_test, y_train, y_test=train_test_split(iris_data,iris_label, test_size=0.2, random_state=11)
#피처 데이터 세트, 레이블 데이터 세트, 테스트 데이터 세트 비율, 호출할 때 마다 같은 학습/테스트데이터 세트를 생성하기 위한 난수발생


In [ ]:
#의사결정트리를 이용한 핟습과 예측 수행
#DecisionTreeClassifier 객체 생성
dt_clf=DecisionTreeClassifier(random_state=11)

In [ ]:
#학습 수행
pred=dt_clf.fit(X_train, y_train)

In [ ]:
#학습데이터가 아닌 다른 데이터(테스트 데이터)로 예측 수행
pred=dt_clf.predict(X_test)

In [10]:
#예측 성능 평가 - accuracy_score(실제 레이블 데이터세트, 예측 레이블 데이터 세트)
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9333


>분류 예측 프로세스
1. 데이터 세트 분리 데이터를 학습 데이터와 테스트 데이터로 분리

2. 모델 학습: 학습된 데이터 기반, ML 알고리즘을 적용해 모델 학습

3. 예측 수행: 학습된 ML모델을 이용, 테스트 데이터 분류 진행

4. 평가: 예측된 결과값과 테스트 데이터의 실제 결괏값을 비교하여 ML모델 성능 평가

###03 사이킷런의 기반 프레임워크 익히기

**Estimator 이해 및 fit(), predict() 메서드**
- 분류 알고리즘 - classifier, 회귀 알고리즘 - regressor로 지칭하며 이를 합쳐 Estimator라 지칭

- cross_val_score()과 같은 evaluation 함수, GridSearchCV와 같은 하이퍼 파라미터 튜닝을 지원하는 클래스의 경우 이 Estimator를 인자로 받으며, 인자로 받은 Estimator에 대해 cross_val_score(), GidSEarchCV.fit()함수

-비지도학습의 fit(): 지도학습의 fit처럼 학습하는 것이 아니라 입력 데이터 형태에 맞춰 데이터를 변환하기 위한 사전 구조를 맞추는 작업
Transform() fit으로 맞춘 입력데이터에 대해 차원변환, 클러스터링, 피처추출




**사이킷런의 주요모듈**
> 예제데이터
- sklearn.datasets 사이킷런에 내장되어 예제로 제공하는 데이터 세트


> 피처처리
- sklearn.preprocessing 데이터 전처리에 필요한 다양한 가공기능 제공(문자열을 숫자형 코드값으로 인코딩, 정규화, 스케일링 등
- Sklearn, feature_selection 알고리즘에 큰 영향을 미치는 피처를 우선순위대로 셀렉션 작업을 수행하는 다양한 기능 제공
- Sklearn.feature_extraction 텍스트 데이터나 이미지 데이터의 벡터화된 피처를 추출하는데 사용됨. 예를 들어 텍스트 데이터에서 count vectorizer나 Tt-ldf Vectorizer 등을 생성하는 기능 제공. 
텍스트 데이터의 피처 추출은 sklearn.feature_extraction, text 모듈에, 이미지 데이터의 피처추출은 sklearn.feature_extraction.image 모듈에 지원 API가 있음.


> 피처처리&차원 축소
- sklearn.decomposition 차원 축소와 관련한 알고리즘을 지원하는 모듈로 PCA, NMF, Trncated SVD 등을 통해 차원 축소 가능
데이터 분리, 검증 & 파라미터 튜닝 sklearn.model_selcletion 교차 검증을 위한 학습용/테스트용 분리. 그리드 서치로 최적 파라미터 추출 등의 API 제공


> 평가
- sklearn.metrics 분류, 회귀, 클러스터링, 페어와이즈에 대한 다양한 성능 측정 방법 제공(Accuracy, Precision, Recall, ROC-AUC, RMSE 등 제공)


> ML 알고리즘
- Sklearn.ensemble 앙상블 알고리즘 제공, 랜덤 포레스트, 에이다 부스트, 그래디언트 부스팅 등 제공
- Sklearn.linear_model 주로 선형회귀, 릿지, 라쏘 및 로지스틱 회귀 등 회귀 관련 알고리즘 지원 및 SGD(stochastic Gradient Descent) 관련 알고리즘도 제공
- Sklearn.naive_bayes 나이브 베이즈 알고리즘 제공, 가우시안 NB, 다항 분포 NB 등
- Sklearn.neighbors 최근접 이웃 알고리즘 제공. K-NN 등
- Sklearn.svm 서포트 벡터 머신 알고리즘 제공
- Sklearn.tree 의사결정 트리 알고리즘 제공
- Sklearn.cluster 비지도 클러스터링 알고리즘 제공(K-평균, 계층형, DBSCAN 등)


> 유틸리티
- Sklearn.pipeline 피처처리 등의 변환과 ML 알고리즘 학습, 예측 등을 함께 묶어서 진행할 수 있는 유틸리티 제공




**내장된 예제 데이터 세트 **
>분류나 회귀 연습용 예제 데이터
- Datasetsl.load_boston() 회귀 용도, 미국 보스턴의 집 피처들과 가격
- Datasetsl.load 분류 용도, 위스콘신 유방암 피처와 악성/음성 레이블 데이터 세트
- Datasetsl.load 회귀 용도, 당뇨 데이터 세트
- Datasetsl.load 분류 용도, 0에서 9까지 숫자의 이미지 픽셀 데이터
- Datasetsl.load 분류 용도, 붓꽃에 대한 피처를 가진 데이터 세트

>Fetch 계열
- Fetch_covtype() 회귀분석용 토지조사자료
- Fetch_20newsgroups() 뉴스 그룹 텍스트 자료
- Fetch_ oliverti_faces() 얼굴 이미지 자료
- Fetch_lfw_people()얼굴 이미지 자료
- Fetch_lfw_pairs()얼굴 이미지 자료
- Fetch_rcv1() 로이터 뉴스 말뭉치
- Fetch_mldata() ML 웹사이트에서 다운로드

>분류와 클러스터링을 위한 표본데이터
- Datasets,make_classification 분류를 위한 데이터 세트 생성, 높은 상관도와 불필요한 속성 등 노이즈 효과를 위한 데이터를 무작위로 생성
- Datasets,make_blobs() 클러스터링을 위한 데이터 세트를 무작위로 생성, 군집 지정 개수에 따라 여러 클러스터링을 위한 데이터 세트를 쉽게 생성



*개별 키 속 데이터세트의 의미

1) Data – 피처의 데이터 세트 (넘파이 배열)

2) Target – 분류 시 레이블 값, 회귀일 때는 숫자 결괏값 데이터 세트 (넘파이 배열)

3) Target_names – 개별 레이블의 이름 (넘파이 배열 또는 파이썬 리스트 타입)

4) Feature_names – 피처의 이름 (넘파이 배열 또는 파이썬 리스트 타입)

5) DESCR – 데이터 세트에 대한 설명과 각 피처의 설명 (스트링 타입)



In [6]:
from sklearn.datasets import load_iris
iris_data=load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


In [8]:
keys = iris_data.keys()
print('붓꽃데이터 세트의 키들: ', keys)

붓꽃데이터 세트의 키들:  dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [14]:
print('\n feautre names의 type: ', type(iris_data.feature_names))
print('feautre names의 shape: ', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 type: ', type(iris_data.target_names))
print('target_names의 shape: ', len(iris_data.feature_names))
print(iris_data.target_names)

print('\n data의 type: ', type(iris_data.data))
print('data의 shape: ', len(iris_data.data.shape))
print(iris_data['data'])

print('\n target의 type: ', type(iris_data.target))
print('target의 shape: ', len(iris_data.target.shape))
print(iris_data.target)


 feautre names의 type:  <class 'list'>
feautre names의 shape:  4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type:  <class 'numpy.ndarray'>
target_names의 shape:  4
['setosa' 'versicolor' 'virginica']

 data의 type:  <class 'numpy.ndarray'>
data의 shape:  2
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3

###04 Model Selection 모듈 소개

**학습/ 테스트 데이터 세트 분리 – train_test_split()**


In [16]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris=load_iris()
dt_clf=DecisionTreeClassifier()
train_data=iris.data
train_label=iris.target
dt_clf.fit(train_data, train_label)

#학습데이터 세트로 예측 수행
pred=dt_clf.predict(train_data)
print('예측정확도:', accuracy_score(train_label, pred))


예측정확도: 1.0


1) train_Test_split()에서 피처데이터 세트, 레이블 데이터 세트 이후 선택적으로 다음 파라미터 입력받음

- Test_size 전체 데이터에서 테스트 데이터 세트를 얼마로 샘플링 할 것인가. 디폴트-0.25
- Train_size 학습용 데이터 세트의 비율
- Shuffle 데이터 분리 전 미리 섞을지 여부로 디폴트는 True
- Random_State 호출 때마다 동일한 데이터 생성을 위한 난수 값
- Train_test_split()의 반환 값은 튜플 값으로 학습용 데이터의 피처 데이터 세트, 테스트용 데이터의 피처 데이터 세트, 학습용 데이터의 레이블 데이터 세트, 테스트용 데이터의 레이블 데이터 세트 반환

In [20]:

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

dt_clf=DecisionTreeClassifier()
iris=load_iris()

X_train, X_test, y_train, y_test=train_test_split(iris_data.data, iris_data.target,test_size=0.3, random_state=121)


In [22]:
dt_clf.fit(X_train, y_train)
pred=dt_clf.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9556


**교차검증**

- 앞서 언급한 테스트용 데이터 또한 과적합(실제 데이터에 성능 감소) 문제 발생 가능성이 있어 교차 검증을 진행함
데이터 편중을 막기 위해 별도의 여러 세트로 구성된 학습 데이터 세트와 검증 데이터 세트에서 학습과 평가를 수행하느 것으로 1차 평가 후 최종적으로 테스트 데이터 세트에 적용해 평가하는 프로세스
- ML에 사용하는 데이터 세트를 세분화하여 학습, 검증, 테스트 데이터 세트로 구분하여 사용



**K 폴드 교차 검증**

:K개의 데이터 폴드세트를 만들어 K번만큼 각 폴드 세트에 학습과 검증 평가를 반복적으로 수행하는 방법
예시로 5 폴드 교차검증을 할 경우 5개의 폴드된 데이터 세트를 학습과 검증을 위한 데이터 세트로 변경하면서 5번 평가를 수행한 뒤, 이 5개의 평가를 평균한 결과를 통해 예측 성능을 평가

1) 데이터 세트를 K 등분

2) 첫 번째 반복에서는 처음부터 4등분을 학습데이터 세트, 5번째 등분 하나를 검증 데이터 세트로 설정하고 학습 데이터 세트에서 학습 수행, 검증 데이터 세트에서 평가 수행

3) 첫 번째 평가 수행 후 두 번째 반복에서는 학습 데이터와 검증 데이터를 처음부터 3개등분까지, 마지막 마지막 5번째 등분을 학습데이터로, 4번째 등분 하나를 검증 데이터 세트로 설정하는 등 순서를 바꾸어 진행

4) 이를 반복하여 5번 진행



In [27]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris=load_iris()
features=iris.data
label=iris.target
dt_clf=DecisionTreeClassifier(random_state=156)

#5개의폴드세트로분리하는 KFold 객체와 폴드세트별 정확도를 담을 리스트 객체 생성
kfold=KFold(n_splits=5)
cv_accuracy=[]
print('붓꽃 데이터 세트 크기:', features.shape[0])


붓꽃 데이터 세트 크기: 150


In [28]:
n_iter=0
#KFold 객체의 split()를 호출 시 폴드 별 학습용,검증용 테스트의 로우 인덱스를 array로 변환
for train_index, test_index in kfold.split(features):
  #Kfold.split()으로 반환된 인덱스를 이용해 학습용 검증용 테스트 데이터 추출
  X_train, X_test=features[train_index],features[test_index]
  y_train,y_test=label[train_index],label[test_index]
  #학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred=dt_clf.predict(X_test)
  n_iter+=1
  #반복 시 마다 정확도 측정
  accuracy=np.round(accuracy_score(y_test, pred),4)
  train_size=X_train.shape[0]
  test_size=X_test.shape[0]
  print('\n#{0} 교차검증정확도 :{1}, 학습데이터크기: {2}, 검증데이터크기: {3}'.format(n_iter, accuracy, train_size,test_size))
  print('#{0} 검증세트인덱스 :{1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

  #개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균검증정확도: ', np.mean(cv_accuracy))



#1 교차검증정확도 :1.0, 학습데이터크기: 120, 검증데이터크기: 30
#1 검증세트인덱스 :[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차검증정확도 :0.9667, 학습데이터크기: 120, 검증데이터크기: 30
#2 검증세트인덱스 :[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차검증정확도 :0.8667, 학습데이터크기: 120, 검증데이터크기: 30
#3 검증세트인덱스 :[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차검증정확도 :0.9333, 학습데이터크기: 120, 검증데이터크기: 30
#4 검증세트인덱스 :[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차검증정확도 :0.7333, 학습데이터크기: 120, 검증데이터크기: 30
#5 검증세트인덱스 :[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균검증정확도:  0.9


** Stratified K 폴드

- 불균형한 분포도를 가진 레이블(결정 클래스) 데이터 집합을 위한 K 폴드 방식으로 K 폴드가 레이블 데이터 집합이 원본 데이터 집합의 레이블 분포를 학습 및 테스트 세트에 제대로 분배하지 못하는 경우의 문제를 해결
- K fold 로 분할된 레이블 데이터 세트가 전체 레이블 값의 분포도를 반영하지 못하는 문제를 해결,
단 split() 메서드 인자로 피처 데이터 세트뿐만 아니라 레이블 데이터 세트 또한 필요



In [29]:
import pandas as pd
iris=load_iris()
iris_df=pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [35]:
kfold=KFold(n_splits=3)
n_iter=0
for train_index, test_index in kfold.split(iris_df):
  n_iter+=1
  label_train=iris_df['label'].iloc[train_index]
  label_test=iris_df['label'].iloc[test_index]
  print('##교차검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포: \n', label_train.value_counts())
  print('검증 레이블 데이터 분포: \n', label_test.value_counts())
  iris_df['label'].value_counts()

##교차검증: 1
학습 레이블 데이터 분포: 
 1    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 0    50
Name: label, dtype: int64
##교차검증: 2
학습 레이블 데이터 분포: 
 0    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 1    50
Name: label, dtype: int64
##교차검증: 3
학습 레이블 데이터 분포: 
 0    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 2    50
Name: label, dtype: int64


In [37]:
from sklearn.model_selection import StratifiedKFold

skf=StratifiedKFold(n_splits=3)
n_iter=0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
  n_iter+=1
  label_train=iris_df['label'].iloc[train_index]
  label_test=iris_df['label'].iloc[test_index]
  print('##교차검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포: \n', label_train.value_counts())
  print('검증 레이블 데이터 분포: \n', label_test.value_counts())

##교차검증: 1
학습 레이블 데이터 분포: 
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 0    17
1    17
2    16
Name: label, dtype: int64
##교차검증: 2
학습 레이블 데이터 분포: 
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 0    17
2    17
1    16
Name: label, dtype: int64
##교차검증: 3
학습 레이블 데이터 분포: 
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 1    17
2    17
0    16
Name: label, dtype: int64


In [41]:
dt_clf=DecisionTreeClassifier(random_state=156)

skfold=StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

#StratifiedKFold의 split()호출 시 반드시 레이블 데이터 세트도 추가입력 필요
for train_index, test_index in skfold.split(features, label):
  #split()으로 반환된 인덱스를 이용해 학습용 검증용 테스트 데이터 추출
  X_train, X_test=features[train_index],features[test_index]
  y_train, y_test=label[train_index],label[test_index]
  #학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred=dt_clf.predict(X_test)
  #반복 시 마다 정확도 측정
  n_iter+=1
  accuracy=np.round(accuracy_score(y_test, pred),4)
  train_size=X_train.shape[0]
  test_size=X_test.shape[0]
  print('\n#{0} 교차검증정확도 :{1}, 학습데이터크기: {2}, 검증데이터크기: {3}'.format(n_iter, accuracy, train_size,test_size))
  print('#{0} 검증세트인덱스 :{1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

  #교차검증별 정확도 및 평균 정확도 
print('\n## 교차검증별 정확도: ', np.round(cv_accuracy, 4))
print('\n## 평균검증정확도: ', np.mean(cv_accuracy))



#1 교차검증정확도 :0.98, 학습데이터크기: 100, 검증데이터크기: 50
#1 검증세트인덱스 :[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차검증정확도 :0.94, 학습데이터크기: 100, 검증데이터크기: 50
#2 검증세트인덱스 :[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차검증정확도 :0.98, 학습데이터크기: 100, 검증데이터크기: 50
#3 검증세트인덱스 :[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차검증별 정확도:  [0.98 0.94 0.98]

## 평균검증정확도:  0.9666666666666667


**교차 검증을 보다 간편하게 – cross_val_score()**

KFold의 일련 과정을 한꺼번에 수행해주는 API, 

Cross_val_score(estimator, X, y=None, scoring=None, cv=None, n_jobs=1, verbose=0, fit_params=Npne, pre_dispatch=’2*njobs’).

순서대로 사이킷런의 분류 알고리즘 클래스인 Classifier 또는 회귀 알고리즘 클래스인 Regressor, X는 피처데이터 세트, 레이블 데이터 세트, 예측 성능평가 지표, 교차 검증 폴드 수, 반환값은 scoring 파라미터로 지정된 성능 지표 측정값의 배열 형태


Cv로 지정된 횟수만큼 scoring 파라미터로 지정된 평가지표로 평가 결괏값을 배열로 반환하며 이를 평균하여 평가 수치로 사용하고 유사 API로는 여러 평가지표를 반환할 수 있는 cross_validate()가 있음


In [43]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data=load_iris()
df_clf=DecisionTreeClassifier(random_state=156)

data=iris_data.data
label=iris_data.target

#성능지표는 정확도(accuracy), 교차 검증 세트는 3개
scores=cross_val_score(df_clf, data, label,scoring='accuracy', cv=3)
print(' 교차 검증별 정확도: ', np.round(scores, 4))
print('평균 검증 정확도: ', np.round(np.mean(scores),4))

 교차 검증별 정확도:  [0.98 0.94 0.98]
평균 검증 정확도:  0.9667


**GridSearchCv – 교차 검증과 최적 하이퍼 파라미터 튜닝을 한번에**

촘촘하게 파라미터를 입력하면서 테스트를 하는 방식, 결정 트리 알고리즘의 여러 하이퍼 파라미터를 순차적으로 변경하면서 최고 성능을 가지는 파라미터 조합을 찾고자 한다면 다음과 같이 진행 가능


순번 max_depth min_samples_split

1 1	2

2	1	3

3	2	2

4	2	3

5	3	2

6	3	3

교차 검증 기반의 하이퍼 파라미터의 최적값을 찾는 것을 도와주는 API, cross_validation을 위한 학습/테스트 세트로 자동분할 뒤 하이퍼 파라미터 그리드에 기술된 모든 파라미터를 순차적으로 적용해 최적의 파라미터를 찾을 수 있게 해줌


*생성자의 주요 파라미터
-	Estimator : classifier, regressor, pipeline이 사용될 수 있음
-	Param_gid: key+리스트 값을 가지는 딕셔너리 주어짐. Estimator의 튜닝을 위해 파라미터명과 사용될 여러 파라미터값을 지정
-	Scoring: 예측 성능을 측정할 평가방법을 지정. 사이킷런의 성능평가 지표를 지정하는 문자열로 지정하나 별도의 성능 평가 지표함수도 지정 가능
-	Cv: 교차 검증을 위해 분할되는 학습/테스트 세트 개수 지정
-	Refit: 디폴트가 True이며 True로 생성 시 가장 최적의 하이퍼 파라미터를 찾은 뒤 입력된 estimator를 찾은 뒤 입력된 estimator 객체를 해당 하이퍼 파라미터로 재학습


In [51]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np

#data loading and seperating train data& test data
iris=load_iris()
X_train, X_test, y_train, y_tesdt=train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)

dtree=DecisionTreeClassifier()

###파라미터를 딕셔너리 형태로 설정
parameters={'max_depth':[1,2,3],'min_samples_split':[2,3]}

In [52]:
import pandas as pd
from sklearn.model_selection import GridSearchCV

#param_grid의 하이퍼파라미터를 3개의 train, test set fold로 나누어 테스트 수행 설정
### refit=True가 default. True이면 가장 좋은 파라미터 설정으로 재학습
grid_dtree=GridSearchCV(dtree,param_grid=parameters,cv=3,refit=True)
#붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train,y_train)

#GridSearchCV 결과 추출하여 DataFRame 변환
scores_df=pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

주요 칼럼별 의미
-	Params 칼럼에는 수행시마다 적용 된 개별 하이퍼 파라미터값
-	Rank_test_score는 하이퍼 파라미터별 성능이 좋은 score 순위를 제시, 1이 가장 뛰어난 최적의 하이퍼 파라미터
-	Mean_test-score는 개별 하이퍼 파라미터 별 CV의 폴딩테스트 세트에 대한 총 수행한 평가 평균값



In [54]:
print('gridserachCV 최적파라미터: ', grid_dtree.best_params_)
print('gridserachCV 최고 정확도: {0:.4f}'.format(grid_dtree.best_score_))


gridserachCV 최적파라미터:  {'max_depth': 3, 'min_samples_split': 2}
gridserachCV 최고 정확도: 0.9750


In [55]:
#gridserachcv의 refit으로이미학습된 estimator 반환
estimator= grid_dtree.best_estimator_

#gridserachcv의 best_estimator는이미 최적학습이 됐으므로 별도 학습 필요X
pred=estimator.predict(X_test)
print('테스트데이터세트정확도:{0:.4f}'.format(accuracy_score(y_test, pred)))

테스트데이터세트정확도:0.9800


### 데이터 전처리

결손값은 허용 X, 다른 고정값, 예를 들어 평균으로 대체할 수 도있으나 결손값 자체가 많은 경우 아예 드롭하는 것이 좋으며 신중히 결정할 필요 있음

**데이터 인코딩**

- 레이블 인코딩
: 카테고리 피처를 코드형 숫자값으로 변환, 예를 들어 티비, 냉장고, 선풍기가 있다면 티비:!, 냉장고:2, 선풍기:3 등으로 변환하는 것으로 문자형을 숫자형으로 변환


In [57]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자레인지','컴퓨터', '선풍기',' 선풍기','믹서','믹서']

#LabelsEncoder를 객체로 생성 후 fit()과 Transform()으로 레이블 인코딩 수행
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print('인코딩변환값: ',labels)

인코딩변환값:  [1 2 5 6 4 0 3 3]


In [58]:
print('인코딩클래스: ',encoder.classes_)

인코딩클래스:  [' 선풍기' 'TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [60]:
print('디코딩원본값: ',encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩원본값:  ['선풍기' '전자레인지' '냉장고' ' 선풍기' 'TV' 'TV' '믹서' '믹서']


- 원-핫 인코딩(One-Hot Encoding)
: 피처 값의 유형에 따라 새로운 피처를 추가해 고유값에 해당하는 칼럼에만 1을 표시하고 나머지에는 0을 표시하는 방식, 여러 개의 속성 중 단 한 개의 속성만 1로 표시
단 문자열 값이 모두 숫자로 변환되어 있어야 하며 [링크 텍스트](https://)입력값으로 2차원 데이터가 필요



In [63]:

from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자레인지','컴퓨터', '선풍기',' 선풍기','믹서','믹서']

#숫자값 반환을 위해 LabelsEncoder로 변환
encoder=LabelEncoder()
encoder.fit(items)
#2차원데이터변환
labels=labels.reshape(-1, 1)

#원핫인코딩 적용 
oh_encoder=OneHotEncoder()
oh_encoder.fit(labels)
oh_labels=oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 차원')
print(oh_labels.shape)


원-핫 인코딩 데이터
[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 차원
(8, 7)


In [65]:
import pandas as pd
df=pd.DataFrame({'item':['TV','냉장고', '전자레인지',' 컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

item_ 컴퓨터  item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지
0          0        1         0        0         0           0
1          0        0         1        0         0           0
2          0        0         0        0         0           1
3          1        0         0        0         0           0
4          0        0         0        0         1           0
5          0        0         0        0         1           0
6          0        0         0        1         0           0
7          0        0         0        1         0           0

**피처 스케일링과 정규화**

서로 다른 변수의 값 범위를 일정 수준으로 맞추는 작업을 피처 스케일링이라 하며 대표적인 방법으로는 표준화와 정규화
표준화 - 데이터의 피처 각각이 평균이 0이고 분산이 1인 가우시안 정규 분포를 따르는 값으로 변


**StandardScaler**
표준화를 쉽게 지원하기 위한 클래스


In [71]:
from sklearn.datasets import load_iris
import pandas as pd

#붓꽃데이터세트로딩, Dataframe으로변환
iris=load_iris()
iris_data=iris.data
iris_df=pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('mean of features')
print(iris_df.mean())
print('variance of \nfeature')
print(iris_df.var())

mean of features
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
variance of 
feature
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [76]:
from sklearn.preprocessing import StandardScaler

#StandardScaler 객체생성
scaler=StandardScaler()
#StandardScaler로데이터세트변환. fit()과 transform()호출
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)

#transform()시 스케일변환된 데이터세트가 numpy ndarray로 반환돼 이를 DataFrame 변환
iris_df_sclaed=pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('mean of features')
print(iris_df.mean())
print('variance of \nfeature')
print(iris_df.var())

mean of features
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
variance of 
feature
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


**MinMaxScaler**

데이터값을0과 1사이의 범위값으로 변환하며 데이터의 분포가 가우시안 분포가 아닐 때 적용 가능


In [77]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()

scaler.fit(iris_data)
iris_scaled=scaler.transform(iris_df)

#transform()시 스케일 변환된 데이터 세트가 NumPy ndarray로 반환돼 이를 DAtaframe으로 변환
iris_df_scaled=pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('min of features')
print(iris_df_scaled.min())
print('max of \nfeature')
print(iris_df_scaled.max())

min of features
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
max of 
feature
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


**학습 데이터와 테스트 데이터의 스케일링 변환 시 유의점**

학습 데이터로 fit()을 적용했을경우 테스트 데이터에도 그대로 적용해야 하며, 테스트 데이터로 다시 새로운 스케일링 기준 정보를 만들어서는 안됨

가능하다면 전체 데이터의 스케일링 변환을 적용 뒤 학습과 테스트 데이터로 분리
1이 여의치 않다면 테스트 데이터 변환 시에는 Fit()이나 fit_transform()을 적용하지 않고 학습 데이터로 이미 fit()된 Sclaer 객체를 이용해 transform()으로 변환


In [78]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

#0-10 in train data, 0-5 in test data
#fit(), trnasform() of Scaler class can use 2차원이상의데이터, so reshape(-1, 1)
train_array=np.arange(0,11).reshape(-1, 1)
test_array=np.arange(0,6).reshape(-1, 1)

In [79]:
#MinMaxScaler에 파라미터값 지정 없을경우 0-1로 변환
scaler=MinMaxScaler()

#fit()>min=0, max=10
scaler.fit(train_array)

#1/10 scale train_array 데이터변환, 원본 10>1
train_scaled=scaler.transform(train_array)

print('원본train_array',np.round(train_array.reshape(-1),2))
print('Scaled train_array',np.round(train_scaled.reshape(-1),2))

원본train_array [ 0  1  2  3  4  5  6  7  8  9 10]
Scaled train_array [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [80]:
#fit()>min=0, max=5
scaler.fit(test_array)

#1/5 scale train_array 데이터변환, 원본 5>1
test_scaled=scaler.transform(test_array)

print('원본 test_array',np.round(test_array.reshape(-1),2))
print('Scaled test_array',np.round(test_scaled.reshape(-1),2))

원본 test_array [0 1 2 3 4 5]
Scaled test_array [0.  0.2 0.4 0.6 0.8 1. ]


In [81]:
scaler=MinMaxScaler()
scaler.fit(train_array)
train_scaled=scaler.transform(train_array)
print('원본 train_array 데이터', np.round(train_array.reshape(-1),2))
print('Scaled train_array',np.round(train_scaled.reshape(-1),2))

#test_array에 Scale 변환시반드시 transform()
test_scaled=scaler.transform(test_array)
print('\n원본 test_array',np.round(test_array.reshape(-1),2))
print('Scaled test_array',np.round(test_scaled.reshape(-1),2))

원본 train_array 데이터 [ 0  1  2  3  4  5  6  7  8  9 10]
Scaled train_array [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array [0 1 2 3 4 5]
Scaled test_array [0.  0.1 0.2 0.3 0.4 0.5]
