<a href="https://colab.research.google.com/github/tamburins/ESAA-2022-/blob/main/ESSA_week1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**03 넘파이**

:Numerical python,선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
-매우 빠른 배열 연산이 가능하나 파이썬 언어 자체의 제약으로 인해 C/C++과 호환하여 작성 후 넘파이에서 호출하기도 함
ex) tensorflow

-배열 기반 연산으로 판다스에 비하면 부족하나 머신러닝 알고리즘이 넘파이 기반으로 작성되어 있기 때문에 파이썬 기반의 머신러닝에서 매우 중요



**넘파이 ndarray 개요**

- numpy만 해도 되지만 as np를 추가하여 약어로 모듈 표현 가능하며 array()함수는 파이썬의 리스트와 같은 다양한 인자를 입력받아 ndarray로 변환하는 기능을 수행하고,

- 생성된 ndarray 배열의 shape변수는 ndarray의 크기(행과 열의 수)를 튜플 형태로 가져 이를 통해 배열의 차원까지 파악 가능


In [ ]:
import numpy as np
array1=np.array([1,2,3])
print('array1 type: ', type(array1))
print('array1 array 형태: ', array1.shape)

array2=np.array([[1,2,3], [2,3,4]])
print('array2 type: ', type(array2))
print('array2 array 형태: ', array2.shape)

array3=np.array([[1,2,3]])
print('array3 type: ', type(array3))
print('array3 array 형태: ', array3.shape)

print('array1: {:0}차원, array2: {:0}차원, array3: {:0}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 type:  <class 'numpy.ndarray'>
array1 array 형태:  (3,)
array2 type:  <class 'numpy.ndarray'>
array2 array 형태:  (2, 3)
array3 type:  <class 'numpy.ndarray'>
array3 array 형태:  (1, 3)
array1: 1차원, array2: 2차원, array3: 2차원


np.array()사용법: ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray로 반환,

1) array1> (3.)이라는 튜플을 통해 1차원 array에 3개의 데이터를 포함함을 알 수 있음

2) array2>(2.3)이라는 튜플을 통해 2차원 array로 2개의 행과 3개의 열을 포함함을 알 수 있음

3) array>(1.3)을 통해 1개의 행과 3개의 열을 포함한 2차원 데이터임을 알 수 있음

**ndarray의 데이터 타입**

- ndarray의 데이터값은 숫자값(int, float 포함), 문자열 값, 불 값 모두 가능

- ndarray 내부에서는 같은 데이터 타입만 가능하며 dtype을 활용하여 데이터 타입 확인 가능

In [ ]:
import numpy as np
list1=[1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype) #list의 데이터를 받아 ndarray의 형태가 int임을 확인

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2, array2.dtype) #type이 섞인 리스트를 데이터로 받을 경우 데이터크기가 더 큰 데이터타입으로 형변환 일괄적용
list3=[1,2,3.0]
array3=np.array(list3)
print(array3, array3.dtype) #크기가 더 큰 float형으로 변환

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64') #astype으로 데이터값 타입변경
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1, 2.1, 3.1])
array_int2=array_float1.astype('int32') #float>int변환하면서 소수점 자리수 사라짐
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


**ndarray를 편리하게 생성하기 - arange, zeros, ones**

: 데이터 일괄 초기화 혹은 테스트 데이터에 사용
- arange(): range()와 유사하게 0부터 함수인자값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환해주며 stop값을 디폴트로 요구하나 start값 또한 부여 가능. 이를 활용하여 연속값 부여
- zeros(): 모든 값을 0으로 채운 해당 행,렬(shape)의 ndarray 반환 ( 단 기본 디폴트 float )
- ones():모든 값을 1로 채운 shape의 ndarray 반환 ( 단 기본 디폴트는 float )

In [ ]:
import numpy as np
sequence_array = np.arange(10) #0-9까지의 1차원 ndarray
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
zero_array=np.zeros((3,2), dtype='int32') #3행 2열의 0행렬
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array=np.ones((3,2)) #3행 2열의 1로만 구성된 행렬 형성
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


**ndarray의 차원과 크기를 변경하는 reshape**

darray를 특정 차원 및 크기로 변환하며 원소 개수와 시키는 사이즈가 일치하지 않는 경우(변환이 불가능한 경우) 오류가 발생한다.



In [ ]:
array1=np.arange(10)
print('array1: /n', array1)

array2=array1.reshape(2,5)
print('array2: /n', array2)

array3=array1.reshape(5,2)
print('array3: /n', array3)

array1: /n [0 1 2 3 4 5 6 7 8 9]
array2: /n [[0 1 2 3 4]
 [5 6 7 8 9]]
array3: /n [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array1.reshape(4,3) #변형 불가능하여(원소는 9개 변환은 12개) 오류

NameError: ignored

In [ ]:
array1=np.arange(10)
print(array1)

array2=array1.reshape(-1,5) #-1을 사용하면 알아서 호환되는 사이즈로 맞춰서 변환
print('array2 shape: ', array2.shape)

array3=array1.reshape(5,-1)
print('array3 shape: ', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape:  (2, 5)
array3 shape:  (5, 2)


In [ ]:
import numpy as np

array1=np.arange(10)
array4=array1.reshape(-1,4) #행과 열 수는 정수로 불가능한 행렬이라 오류 발생

ValueError: ignored

In [ ]:
# toilist():ndarray를 list자료형으로 변환
import numpy as np

array1=np.arange(8)
array3d=array1.reshape((2,2,2)) #3차원 리스트 생성
print('array3d: \n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1) 
print('array5: \n', array5.tolist())
print('array5 shape: ', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print('array6: \n', array6.tolist())
print('array6 shape: ', array6.shape)



array3d: 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5: 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape:  (8, 1)
array6: 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape:  (8, 1)


**넘파이에서의 ndarry의 데이터세트 선택하기 -인덱싱(indexing)**


1.   특정한 데이터만 추출 : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환

2.   슬라이싱(slicing): 슬라이싱은 연속된 인덱스상의 ndarray를 추출하는 방식으로 'a:b'일 경우 인덱스 a와 b-1인덱스의 ndarray를 반환

3. 팬시 인덱싱(Fancy indexing): 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환

4. 불린 인덱싱(Boolean indexing):특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 데이터의 ndarray를 반환

In [8]:
#단일값추출
#1-9까지의 1차원 ndarray생성
sort_array2d_axis1=np.arange(start=1, stop=10)
print('array1: ',array1)

#index는 0부터 시작하므로 array1[2]는 3번째 값을 의미
value=array1[2] #[] 인덱스위치의 데이터값, not ndarray
print('value: ', value)
print(type(value))
print('맨뒤에값: ',array1[-1],'맨 뒤에서 두번쨰값:', array1[-2])
#-를 이용하여 뒤에서부터의 인덱싱 가능, -2는 뒤에서부터 두번째 데이터

array1[0]=9
array1[8]=0 #단일인덱스를 이용하여 데이터 수정 가능
print('array1: ', array1)


array1:  [9 2 3 4 5 6 7 8 0]
value:  3
<class 'numpy.int64'>
맨뒤에값:  0 맨 뒤에서 두번쨰값: 8
array1:  [9 2 3 4 5 6 7 8 0]


In [ ]:
#다차원 ndarray에서의 데이터 단일값 추출
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3) #9개의 원소 3행 3열 정렬
print(array2d)

print('(row=0, col=0) index 가리키는 값: ',array2d[0,0]) #1행 1열 원소
print('(row=0, col=1) index 가리키는 값: ',array2d[0,1]) #1행 2열 원소
print('(row=1, col=0) index 가리키는 값: ',array2d[1,0]) #2행 1열
print('(row=2, col=2) index 가리키는 값: ',array2d[2,2]) #3행 3열
#정확히는 axis0, axis1이 각각 열과 행을 의미하고 열과 행이라는 용어는 쓰지 않음

**슬라이싱**

:단일 데이터 추출을 제외하고 슬라이싱, 팬시인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray로 [a:b]일 경우 a번째 데이터부터 b-1까지의 데이터 반환

### 1) 1차원 인덱싱


In [9]:

array1=np.arange(start=1, stop=10)
array3=array1[0:3] #인덱스 0, 1, 2의 원소 반환
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array1=np.arange(start=1, stop=10)
aray4=array1[:3] # 시작 인덱스 생략 가능, 이 경우 자동으로 맨 처음 인덱스로 간주
print(array4)

aray5=array1[3:] #종료 인덱스 생략 가능,이 경우 자동으로 맨 끝 인덱스로 간주
print(array5)

aray6=array1[:] #시작과 종료 인덱스 생략 가능,이 경우 자동으로 맨처음/맨마지막 인덱스로 간주
print(array6)

## 2)2차원 ndarray 인덱싱

In [ ]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2]) # 1,2행, 1,2열
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3]) # 2,3행, 1,2,3열
print('array2d[1:3, :] \n', array2d[1:3, :]) #2,3행, 전체열
print('array2d[:, :] \n', array2d[:, :]) #전체 
print('array2d[:2, 1:] \n', array2d[:2, 1:]) #1,2행, 2,3열
print('array2d[:2, 0 ]\n', array2d[:2, 0]) #한쪽은 적용하고 다른 쪽 축에는 단일값 인덱스를 적용해도 됨

print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0 ]
 [1 4]


##2 )팬시 인덱싱

:인덱스 집합을 지정하면 해당 위치 인덱스에 해당하는 ndarray를 반환

In [10]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2]=>', array3.tolist()) #1-2행 3열

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>', array4.tolist()) #혼용 가능

array5=array2d[[0,1]]
print('array2d[[0,1]]=>', array5.tolist()) #뒤에 없으면 자동으로 (0:1),(1:)으로 적용


array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


## 3) 불린 인덱싱

: 조건 필터링과 검색을 동시에 수행 가능


In [14]:
array1d=np.arange(start=1, stop=10)
#[]안에 array1d > 5 Boolean indexing 을 적용
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:', array3)

array1d>5 #단순 조건식 할당만으로 f/t의 ndarray 객체 반환

boolean_indexes=np.array([False, False,False,False,False,True,True,True,True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3) # true가 있는 곳의 데이터만 반환

indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4) #위의 불린 인덱싱과 동일한 결과

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]
불린 인덱스로 필터링 결과: [6 7 8 9]
일반 인덱스로 필터링 결과 : [6 7 8 9]


step1) array1d>5와 같은 ndarray의 필터링 조건을 []안에 게재
step2) False 값을 무시하고 True에 해당하는 인덱스 값만 저장(true값을 가진 인덱스를 저장, true값 자체 저장이 아님)
step3) 저장된 인덱스 데이터 세트로 ndarray 조회

## **행렬의 정렬-sort()와 argsort()**
**행렬 정렬**

1) np.sort()

:
원 행렬 유지상태에서 정렬된 행렬 반환

2) ndarray.sort()

:원행렬 자체를 정렬한 형태로 변환하며 반환값이 none

In [15]:
#행렬 정렬
org_array=np.array([ 3,1,9,5])
print('원본 행렬:', org_array)
#np.sort()로 정렬
sort_array1 =np.sort(org_array)
print('np.sort()호출 후 반환된 행렬:', sort_array1)
print('np.sort()호출 후 원본 행렬:', org_array) #원본은 그대로
#ndarray.sort로 정렬
sort_array2=org_array.sort()
print('org_array.sort()호출 후 반환된 행렬:', sort_array2) #반환 행렬 none
print('org_array.sort()호출 후 원본 행렬:', org_array) #원본도 정렬

sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

원본 행렬: [3 1 9 5]
np.sort()호출 후 반환된 행렬: [1 3 5 9]
np.sort()호출 후 원본 행렬: [3 1 9 5]
org_array.sort()호출 후 반환된 행렬: None
org_array.sort()호출 후 원본 행렬: [1 3 5 9]
내림차순으로 정렬: [9 5 3 1]


In [17]:
#2차원 이상의 행렬에서 axis 축값 설정을 통해 로우 또는 칼럼방향으로 정렬 수행
array2d=np.array([[8,12],
                  [7,1]])
sort_array2d_axis0=np.sort(array2d, axis=0)
print('로우방향으로 정렬:\n', sort_array2d_axis0) #로우가 axis=0

sort_array2d_axis1=np.sort(array2d, axis=1) #axis=1: 열
print('칼럼방향으로 정렬:\n', sort_array2d_axis1)

로우방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


**정렬된 행렬의 인덱스를 반환하기**

In [16]:
org_array=np.array([3,1,5,9])
sort_indices=np.argsort(org_array) #argsort():정렬행렬의 원본행렬 인덱스 반환
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

org_array=np.array([3,1,5,9])
sort_indicies_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indicies_desc)


<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 2 3]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [3 2 0 1]


In [18]:
import numpy as np

name_array=np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])


성적 오름차순 정렬시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


# **선형대수 연산- 행렬 내적과 전치행렬 구하기**

**행렬 내적(행렬곱)**

In [19]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8],[9,10],[11,12]])
dot_product=np.dot(A,B)
print('행렬 내적 결과: \n', dot_product)

행렬 내적 결과: 
 [[ 58  64]
 [139 154]]


**전치 행렬**

: 원 행렬에서 행과 열의 위치를 교환한 원소로 구성한 행렬

In [ ]:
A=np.array([[1,2],[3,4]])
transpose_mat=np.transpose(A)
print('A의 전치행렬: \n', transpose_mat)